const farmersMarkets = {
  data: [
    {
      brief_desc: '',
      contact_email: 'info@montrosefarmersmarket.com',
      contact_name: null,
      contact_phone: '970-323-5756',
      directory_name: 'farmers market',
      directory_type: 'farmersmarket',
      distance: '1000',
      listing_desc: null,
      listing_id: '309099',
      listing_image: 'default-farmersmarket-4-3.jpg',
      listing_name: "Montrose Farmers' Market",
      location_address:
        'S. 1st St. & S. Uncompahgre Ave., At Centennial Plaza, Montrose, CO, 81401',
      location_city: 'Montrose',
      location_state: 'Colorado',
      location_street: 'S. 1st St. & S. Uncompahgre Ave.',
      location_x: '-107.8733232776689',
      location_y: '38.48044865587611',
      location_zipcode: '81401',
      media_blog: null,
      media_facebook: 'https://www.facebook.com/MontroseFarmersMarket',
      media_instagram: null,
      media_pinterest: null,
      media_twitter: null,
      media_website: 'http://www.montrosefarmersmarket.com',
      media_youtube: null,
      mydesc: '',
      term: '',
      updatetime: 'Mar 20th, 2023',
    },
    {
      brief_desc: '',
      contact_email: '',
      contact_name: null,
      contact_phone: '719-592-9420',
      directory_name: 'farmers market',
      directory_type: 'farmersmarket',
      distance: '1000',
      listing_desc: null,
      listing_id: '309100',
      listing_image: 'default-farmersmarket-4-3.jpg',
      listing_name: "Monument Hill Farmers' Market",
      location_address: '146 Jefferson Street Monument, CO 80132',
      location_city: 'Monument',
      location_state: 'Colorado',
      location_street: '146 Jefferson Street',
      location_x: '-104.8707290016444',
      location_y: '39.090785984457824',
      location_zipcode: '80132',
      media_blog: null,
      media_facebook: '',
      media_instagram: null,
      media_pinterest: null,
      media_twitter: null,
      media_website: '',
      media_youtube: null,
      mydesc: '',
      term: '',
      updatetime: 'Mar 20th, 2023',
    },
    {
      brief_desc: '',
      contact_email:
        'info@nocovirtualfarmersmarket.com*candida@nocovirtualfarmersmarket.com',
      contact_name: null,
      contact_phone: '970-402-6002',
      directory_name: 'farmers market',
      directory_type: 'farmersmarket',
      distance: '1000',
      listing_desc: null,
      listing_id: '309101',
      listing_image: 'default-farmersmarket-4-3.jpg',
      listing_name: 'Noco Virtual Farmers Market',
      location_address:
        '3307 South College Avenue, Suite 216 123 North College Ave., Suite 139 Fort Collins, CO 80524',
      location_city: 'Fort Collins',
      location_state: 'Colorado',
      location_street: '3307 South College Avenue',
      location_x: '-105.07757903313151',
      location_y: '40.58782498845264',
      location_zipcode: '80524',
      media_blog: null,
      media_facebook: 'https://www.facebook.com/groups/499722194053286/',
      media_instagram: null,
      media_pinterest: null,
      media_twitter: null,
      media_website: 'https://www.nocovirtualfarmersmarket.com/',
      media_youtube: null,
      mydesc: '',
      term: '',
      updatetime: 'Mar 20th, 2023',
    },
    {
      brief_desc: '',
      contact_email: '',
      contact_name: null,
      contact_phone: '970-658-5198',
      directory_name: 'farmers market',
      directory_type: 'farmersmarket',
      distance: '1000',
      listing_desc: null,
      listing_id: '309102',
      listing_image: 'default-farmersmarket-4-3.jpg',
      listing_name: 'Northern Colorado Winters Market',
      location_address: 'PO Box 1545 Fort Collins, CO 80522',
      location_city: 'Fort Collins',
      location_state: 'Colorado',
      location_street: 'PO Box 1545',
      location_x: '-105.08074499999998',
      location_y: '40.583570000000066',
      location_zipcode: '80522',
      media_blog: null,
      media_facebook: '',
      media_instagram: null,
      media_pinterest: null,
      media_twitter: null,
      media_website: 'https://www.belocalnc.org/',
      media_youtube: null,
      mydesc: '',
      term: '',
      updatetime: 'Mar 20th, 2023',
    },
    {
      brief_desc: '',
      contact_email: '',
      contact_name: null,
      contact_phone: '303-375-5475',
      directory_name: 'farmers market',
      directory_type: 'farmersmarket',
      distance: '1000',
      listing_desc: null,
      listing_id: '309103',
      listing_image: 'default-farmersmarket-4-3.jpg',
      listing_name: 'Northfield Farmers Market',
      location_address:
        'Northfield Farmers Market, 8340 Northfield Boulevard, Denver, CO 80238',
      location_city: 'Denver',
      location_state: 'Colorado',
      location_street: '8340 Northfield Boulevard',
      location_x: '-104.8910088657402',
      location_y: '39.78527660512828',
      location_zipcode: '80238',
      media_blog: null,
      media_facebook: '',
      media_instagram: null,
      media_pinterest: null,
      media_twitter: null,
      media_website:
        'www.stapletondenver.com/whats-happening/stapleton-farmers-market-every-sunday-36043',
      media_youtube: null,
      mydesc: '',
      term: '',
      updatetime: 'Mar 20th, 2023',
    },
    {
      brief_desc: '',
      contact_email: '',
      contact_name: null,
      contact_phone: '970-327-4393',
      directory_name: 'farmers market',
      directory_type: 'farmersmarket',
      distance: '1000',
      listing_desc: null,
      listing_id: '309104',
      listing_image: 'default-farmersmarket-4-3.jpg',
      listing_name: 'Norwood Farm and Craft Market',
      location_address: '1165 Summit Street Norwood, CO 81423',
      location_city: 'Norwood',
      location_state: 'Colorado',
      location_street: '1165 Summit Street',
      location_x: '-108.29652518750727',
      location_y: '38.13177756667583',
      location_zipcode: '81423',
      media_blog: null,
      media_facebook: '',
      media_instagram: null,
      media_pinterest: null,
      media_twitter: null,
      media_website: 'https://www.norwoodfarmmarket.org/',
      media_youtube: null,
      mydesc: '',
      term: '',
      updatetime: 'Mar 20th, 2023',
    },
  ],
};

export default farmersMarkets;
